# Generated by Django 4.2.9 on 2024-02-26 10:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookingdetails",
            name="date_care_is_needed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userbookingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0e3e5475-4754-4005-97da-00c635be1b46"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
