# Generated by Django 4.2.9 on 2024-02-26 13:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_userbookingdetails_date_care_is_needed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8c50d963-8b14-4706-ad96-f59aeeb1bcee"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userbookingdetails",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("requested", "requested"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("succeeded", "succeeded"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
