# Generated by Django 4.2.9 on 2024-02-27 07:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_userbookingdetails_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookingdetails",
            name="date_care_is_needed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userbookingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("82d306b4-ee87-405f-acbc-9f26df44428d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
