# Generated by Django 4.2.9 on 2024-02-29 19:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_userbookingdetails_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6e388fda-b31a-47c4-a86c-8352e25ea4f4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
