# Generated by Django 4.2.9 on 2024-03-02 11:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0006_alter_userbookingdetails_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("eba4e644-4857-40fe-8e1d-84ab06023da3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userbookingdetails",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practitioner_booking_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
