# Generated by Django 4.2.9 on 2024-03-13 20:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_userbookingdetails_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
