# Generated by Django 4.2.9 on 2024-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_userbookingdetails_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookingdetails",
            name="date_time_of_care",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userbookingdetails",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("requested", "requested"),
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("succeeded", "succeeded"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
