# Generated by Django 4.2.9 on 2024-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_userbookingdetails_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralBookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_consultation",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
    ]
