# Generated by Django 4.2.9 on 2024-05-25 20:55

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_generalbookingdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBookingRequestTimeFrame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_timeframe",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateTimeField(blank=True, null=True),
                        size=None,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_request_timeframe",
                        to="booking.userbookingdetails",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
