# Generated by Django 4.2.9 on 2024-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_userbookingrequesttimeframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookingdetails",
            name="eta",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
