# Generated by Django 4.2.9 on 2024-01-25 13:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emailaddressverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6cfcda5c-5284-45be-9a81-55370a22e8f8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6cfcda5c-5284-45be-9a81-55370a22e8f8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6cfcda5c-5284-45be-9a81-55370a22e8f8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("314a79d0-cf46-44f3-92eb-c9c24ebfde76"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
