# Generated by Django 4.2.9 on 2024-01-25 14:19

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_user_state_alter_emailaddressverification_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaddressverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e7ea0e0b-efed-46bf-b4ab-a39567270baa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e7ea0e0b-efed-46bf-b4ab-a39567270baa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e7ea0e0b-efed-46bf-b4ab-a39567270baa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b8d6ef82-9396-48d0-ab34-a54a50496908"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="languages_spoken",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                size=None,
            ),
        ),
    ]
