# Generated by Django 4.2.9 on 2024-01-27 19:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_user_photo_alter_emailaddressverification_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.AlterField(
            model_name="emailaddressverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("984d414a-c9ac-41f4-8be3-f248770dd51f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("984d414a-c9ac-41f4-8be3-f248770dd51f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("984d414a-c9ac-41f4-8be3-f248770dd51f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c2f3ce97-ceaf-4675-a96d-44bb0bc2f324"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
