# Generated by Django 4.2.9 on 2024-01-31 15:23

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_user_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaddressverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b9ca08db-63a0-41ca-97e8-e58633abd297"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b9ca08db-63a0-41ca-97e8-e58633abd297"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b9ca08db-63a0-41ca-97e8-e58633abd297"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1e5fb828-875d-48ec-8ed5-6d1b43e0d232"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="ProviderQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("b9ca08db-63a0-41ca-97e8-e58633abd297"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credentials",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("NPI", models.CharField(blank=True, max_length=255, null=True)),
                ("CAQH", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "languages_spoken",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=255, null=True
                        ),
                        size=None,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_provider_qualification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PractitionerPracticeCriteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("b9ca08db-63a0-41ca-97e8-e58633abd297"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practice_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("max_distance", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "preferred_zip_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=255, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "available_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(blank=True, null=True), size=None
                    ),
                ),
                (
                    "price_per_consultation",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("minimum_age", models.PositiveIntegerField(blank=True, null=True)),
                ("maximum_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_practice_criteria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
