# Generated by Django 4.2.9 on 2024-02-06 12:42

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_emailaddressverification_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="providerqualification",
            old_name="credentials",
            new_name="credential_title",
        ),
        migrations.RenameField(
            model_name="providerqualification",
            old_name="languages_spoken",
            new_name="licensed_states",
        ),
        migrations.AddField(
            model_name="providerqualification",
            name="practioner_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emailaddressverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da6fac40-58b4-45fe-bf26-406432a3044f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da6fac40-58b4-45fe-bf26-406432a3044f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da6fac40-58b4-45fe-bf26-406432a3044f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerpracticecriteria",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da6fac40-58b4-45fe-bf26-406432a3044f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="providerqualification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da6fac40-58b4-45fe-bf26-406432a3044f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7b7166fe-8e7f-4825-8f09-c0eb7b64af9d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="PractitionerAdditionalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_of_zip_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=255, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_practice_Practitioner_zip_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
