# Generated by Django 4.2.9 on 2024-02-12 13:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0007_rename_credentials_providerqualification_credential_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8f5bd5e0-837f-43ce-b025-2d2aa5a966f9"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("token", models.CharField(max_length=9, unique=True)),
                ("sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="practitioneradditionalinformation",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f5bd5e0-837f-43ce-b025-2d2aa5a966f9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f5bd5e0-837f-43ce-b025-2d2aa5a966f9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerpracticecriteria",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f5bd5e0-837f-43ce-b025-2d2aa5a966f9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="providerqualification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f5bd5e0-837f-43ce-b025-2d2aa5a966f9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("25eb11a5-1331-436d-b296-0032149307aa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="EmailAddressVerification",
        ),
        migrations.DeleteModel(
            name="PractitionerAdditionalInformation",
        ),
    ]
