# Generated by Django 4.2.9 on 2024-02-12 13:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_emailconfirmation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmation",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f994de5-0387-4b7d-a8f8-b67d7f6acc36"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f994de5-0387-4b7d-a8f8-b67d7f6acc36"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f994de5-0387-4b7d-a8f8-b67d7f6acc36"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerpracticecriteria",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f994de5-0387-4b7d-a8f8-b67d7f6acc36"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="providerqualification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f994de5-0387-4b7d-a8f8-b67d7f6acc36"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bb5be7ff-683b-4cfd-b4da-b6344b2ca8b3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
