# Generated by Django 4.2.9 on 2024-02-12 21:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_phonenumberverification_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonenumberverification",
            name="user",
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3e55028-afc8-4003-9162-c3cbad06c8d5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3e55028-afc8-4003-9162-c3cbad06c8d5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3e55028-afc8-4003-9162-c3cbad06c8d5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerpracticecriteria",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3e55028-afc8-4003-9162-c3cbad06c8d5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="providerqualification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3e55028-afc8-4003-9162-c3cbad06c8d5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a78b471b-221a-4421-8ee9-7f235516a681"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
