# Generated by Django 4.2.9 on 2024-03-13 20:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0019_alter_emailconfirmation_id_alter_passwordreset_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberverification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerpracticecriteria",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="providerqualification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("98e9fa0a-e5ae-43c7-aa47-74d081438d6e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="PractitionerAvailableDateTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("af7975a0-1c39-4e02-9c94-c2ded6360cbb"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_available_date_time",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="practitionerpracticecriteria",
            name="available_date_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.practitioneravailabledatetime",
            ),
        ),
    ]
