# Generated by Django 4.2.9 on 2024-03-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0022_alter_practitioneravailabledatetime_provider_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitionerpracticecriteria",
            name="maximum_age",
        ),
        migrations.RemoveField(
            model_name="practitionerpracticecriteria",
            name="minimum_age",
        ),
        migrations.AddField(
            model_name="practitionerpracticecriteria",
            name="age_range",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
