# Generated by Django 4.2.9 on 2024-03-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0023_remove_practitionerpracticecriteria_maximum_age_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitioneravailabledatetime",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="practitionerpracticecriteria",
            name="available_date_time",
        ),
        migrations.AddField(
            model_name="practitioneravailabledatetime",
            name="provider_criteria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_date_time",
                to="authentication.practitionerpracticecriteria",
            ),
        ),
    ]
