# Generated by Django 4.2.9 on 2024-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0024_remove_practitioneravailabledatetime_provider_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="practitionerpracticecriteria",
            name="maximum_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practitionerpracticecriteria",
            name="minimum_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
