# Generated by Django 4.2.9 on 2024-03-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_practitionerpracticecriteria_maximum_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitionerpracticecriteria",
            name="price_per_consultation",
        ),
    ]
