# Generated by Django 4.2.9 on 2024-04-01 14:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0026_remove_practitionerpracticecriteria_price_per_consultation",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurance_company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "insurance_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "insurance_group_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "insured_date_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "patient_relationship",
                    models.CharField(
                        blank=True,
                        choices=[("self", "self"), ("dependent", "dependent")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_insurance_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
