# Generated by Django 4.2.9 on 2024-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_insurancedetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancedetails",
            name="insurance_coverage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="insurancedetails",
            name="self_pay",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="insurancedetails",
            name="insured_date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
