# Generated by Django 4.2.9 on 2024-04-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_insurancedetails_insurance_coverage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancedetails",
            name="insured_date_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
