# Generated by Django 4.2.9 on 2024-05-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_usercard_card_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercard",
            name="payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usercard",
            name="setup_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
