# Generated by Django 4.2.9 on 2024-05-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0034_usercard_cardholder_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercard",
            old_name="cardholder_number",
            new_name="cardholder_name",
        ),
    ]
