# Generated by Django 4.2.9 on 2024-06-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_rename_cardholder_number_usercard_cardholder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerqualification",
            name="speciality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
