# Generated by Django 4.2.9 on 2024-06-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_providerqualification_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="residential_zipcode",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
